Dragoon-Lab/topomath

www/css/state-machine.css
www/index.php
www/js/draw-model.js
www/js/graph-objects.js
www/js/main.js
www/js/model.js
www/problems/rabbits.json

Changes for side node descriptions and event handling for nodes

---

www/css/login-base.css
www/css/login-form.css
www/index.php
www/js/main.js
www/login.html

commit to add login html with page session reload on page refresh and query handling incorporation Resolves #22

Commits login.html for development functionality

---

www/css/login-base.css
www/css/login-form.css
www/js/main.js
www/js/session.js
www/logger.php
www/login.html
www/save_model.php

Changes for saving the model and logging start session. Please let me know for any issues.
Resolves #10 
Accurate diff here: https://github.com/Dragoon-Lab/topomath/compare/master...save_model

save session and solution

---

www/css/global.css
www/index.php
www/js/alert-dialog.js
www/js/con-author.js
www/js/controller.js
www/js/main.js
www/js/popup-dialog.js

Hi Jon, 
These are the changes related to Done Button check and alert dialog. Please review and let me know for any issues.
Thanks,
Dharani

Done Button Changes

---

www/css/global.css
www/index.php
www/js/con-author.js
www/js/controller.js
www/js/equation.js
www/js/graph-objects.js
www/js/main.js
www/js/model.js
www/js/typechecker.js

please review
resolves #31 handleInitial related apply directives and functions, 
resolves #39 handle setStudentEqNode, 
resolves #40 handle setStudentQtyNode

Node editor2 	handleInitial related apply directives and functions, handle setStudentEqNode, handle setStudentQtyNode

---

www/js/con-author.js
www/js/controller.js
www/js/equation.js
www/js/logging.js
www/js/main.js
www/js/model.js
www/js/session.js
www/logger.php
www/problems/rabbits.json

Logger object completely. Initialization done in main and included in controller, to show the working.
Resolves #14, #46

Logging resolves #14 #46

---

www/css/state-machine.css
www/js/draw-model.js
www/js/graph-objects.js
www/js/main.js
www/js/model.js
www/task_fetcher.php

Editor done button and delete node - handles #53 #54 #61 #57

---

www/index.php
www/js/con-author.js
www/js/controller.js
www/js/draw-model.js
www/js/equation.js
www/js/graph-objects.js
www/js/logging.js
www/js/main.js
www/js/model.js

resolves #77 (23746bd) #72 (201a7e7) #68 (201a7e7) #65 (multiple commits) #59 (acc4e54) #12 (f655369) #73 (f46cfd5) #96 (52f9245)

Node editor ui integration changes

---

www/js/graph-objects.js

resolves #106 double node on dynamic check was showing when a problem was refreshed. Fixed it by adding an explicit check for value as well.

fix for double node issue

---

www/js/con-author.js
www/js/controller.js
www/js/draw-model.js
www/js/equation.js
www/js/graph-objects.js
www/js/main.js
www/js/model.js
www/problems/rabbits.json

Resolves #100 and double node behavior which was closed earlier.

Show prior in equations and show initial node without value

---

www/js/con-author.js
www/js/controller.js
www/js/draw-model.js
www/js/equation.js
www/js/main.js
www/js/model.js

Reverts Dragoon-Lab/topomath#115
wrongly merged to master. Was intending to merge the other pull request

Revert "Variable type radio buttons"

---

www/index.php
www/js/con-author.js

issue exists only on windows+chrome on certain machines. resolves #119

changes to fix radio buttons not working properly

---

www/color-test.html
www/css/state-machine.css
www/js/draw-model.js
www/js/graph-objects.js

Fix for issues - 
* convert quantity border color to background color #121 
* restructure the colors so that nodes are distinctly understandable. #125

changes to fix the node background color and node description

---

www/index.php
www/js/con-student.js
www/js/controller.js
www/js/customRadioButton.js
www/js/draw-model.js
www/js/main.js
www/js/model.js
www/js/pedagogical_module.js

Equation handling when answer is shown to the student. Resolves #186 #188

Student mode bug fixes

---

www/index.php
www/js/con-student.js
www/js/controller.js
www/js/equation.js

Last minute bug fixes for class day 1

---

www/index.php
www/js/message-box.js
www/js/render-solution.js
www/js/user-messages.js

Static Graph issue fixed

---

www/js/render-solution.js

There was a bug found by @dharanisakary and the branch got merged. This is the fix for the bug and does not have too many changes.

Changes for multiple messages showing on static graph

---

www/js/calculation.js
www/js/con-student.js
www/js/main.js
www/js/render-solution.js
www/js/sliders.js
www/js/tutor-configuration.js
www/js/user-messages.js

fixes graph issues for nofeedback mode and static graphs

---

www/js/render-solution.js
www/js/user-messages.js

also shows the graph of first function node, when no dynamic variables are there in the model

changes for prechecking equation

---

www/js/con-author.js
www/js/controller.js

Eq editor update3

---

www/index.php
www/js/con-author.js
www/js/controller.js
www/js/model.js

addresses #370 #349 (from inside the editor)
PR todos:

Qty editor update2

---

www/js/equation.js
www/js/user-messages.js

Tutor side changes for incorporating new error messages and solver updates for preprocessing the equations.

Topomath side changes for overdetermined system

---

www/index.php
www/js/con-author.js
www/js/controller.js

These changes restrict the user from typing invalid characters into fields.

Restrict text inputs

---

www/js/draw-model.js

A topomath version of this fix: https://github.com/Dragoon-Lab/LaitsV3/pull/92

Fix link deletion being broken on touch devices

---

www/schema-table.json

Merging the current live version to master.

Sharing sedit

---

www/index.php
www/js/con-author.js
www/js/con-student.js
www/js/controller.js
www/js/draw-model.js
www/js/equation.js
www/js/main.js
www/js/model.js
www/js/pedagogical-module.js
www/schema-table.json
www/task_fetcher.php
www/version.js

Issues we should fix before release:
Issues we look at after release:
- When the quantity editor opens, let's change that dialog to not automatically put the cursor in the variable name box.  It changes the color from green to white which could make the user think they didn't get the variable name correct.  
- After deleting an equation, the equation counter does not decrement by 1 (it should).  Check behavior of quantity delete as well.
- On a touch screen, there is a console error when user clicks on the quantity type radio button directly.  (Workaround: click on the text instead).
- When the student gets yellow on the schema field, the message feedback is "You have entered a valid schema", but it should say "The correct answer has been given." like in other fields.
- If the student …

Schema Reconstruction Mode (new version)

---

www/js/con-student.js

Testing bug fixes for ambiguous schema slots (e.g. parts of part whole)
A good test problem is "Age Puzzle" in non-class-models, folder "chapter 3 quiz extras-tca".

Reconstruction Bug Fixes

---

www/js/con-student.js
www/js/controller.js
www/js/equation.js

Bugfix #451 #446 and #455

---

www/js/con-student.js
www/js/controller.js
www/js/main.js

Fixes #421  and #452 and merged latest master

Authors Node Positions and prevent schema control lock

---

www/js/session.js
www/js/tweakModel.js
www/login.html

Please test by toggling switches in login.html. Please toggle them separately while you test each feature

Give parameters and DRTs

---

www/index.php
www/js/con-student.js
www/js/controller.js
www/js/draw-model.js
www/js/equation.js
www/js/main.js
www/js/model.js
www/js/render-solution.js
www/js/session.js
www/js/tweakModel.js
www/js/user-messages.js
www/login.html
www/schema-table.json

issues addressed
https://github.com/Dragoon-Lab/topomath/issues/454
https://github.com/Dragoon-Lab/topomath/issues/471
https://github.com/Dragoon-Lab/topomath/issues/474
https://github.com/Dragoon-Lab/topomath/issues/475
https://github.com/Dragoon-Lab/topomath/issues/473
https://github.com/Dragoon-Lab/topomath/issues/472
https://github.com/Dragoon-Lab/topomath/issues/476
https://github.com/Dragoon-Lab/topomath/issues/477
https://github.com/Dragoon-Lab/topomath/issues/480
https://github.com/Dragoon-Lab/topomath/issues/479
last commit : couple of bugs related to 480 ( no issues for added for them, but need these to test 480 and also 479).

Schema recon2

---

www/database.php
www/global.php

Handles the assignments creation failed bug (name was not being updated on tutor side)

new name parameter for assignments to use updated name

---

www/index.php
www/js/con-student.js
www/js/controller.js
www/js/draw-model.js
www/js/main.js
www/js/model.js
www/js/session.js
www/js/tutor-configuration.js

Addresses issues #478 , #464, #465, and #495.

Issues #478 , #464, #465, and #495
